from sqlalchemy import Boolean, Column, Integer, Float, String, ForeignKey, DateTime, Enum, Date, Time
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from sqlalchemy.dialects.postgresql import ARRAY
from models.base import Base
from datetime import datetime

class Carrier_Shipment(Base):
    __tablename__ = "carrier_shipments"

    id = Column(Integer, primary_key=True, index=True)
    tracking_status = Column(String, nullable=True)
    is_subshipment = Column(Boolean, default=False, nullable=False)
    auction_id = Column(Integer, nullable=True, index=True)
    carrier_lane_id = Column(Integer, nullable=True, index=True)
    client_lane_id = Column(Integer, nullable=True, index=True)
    booking_source = Column(String(50), nullable=False, default="One-Off")
    shipment_reference = Column(String(100), unique=True, index=True)
    booking_reference = Column(String(100), nullable=True, index=True)
    trip_type = Column(String, nullable=False)
    load_type = Column(String, nullable=False)
    carrier_id = Column(Integer, nullable=False)
    carrier_user_id = Column(Integer, nullable=False)
    rate = Column(Numeric(14, 2), nullable=False)
    service_fee = Column(Numeric(14, 2), nullable=True)
    pricing_basis = Column(String(50), nullable=False)
    vat_included = Column(Boolean, nullable=False)
    payment_terms = Column(String, nullable=False)
    invoice_id = Column(Integer, nullable=True)
    invoice_due_date = Column(Date, nullable=True)
    invoice_status = Column(String, nullable=True)
    pickup_date = Column(Date)
    priority_level = Column(String, nullable=True)
    customer_reference_number = Column(String)
    shipment_weight = Column(Integer)
    commodity = Column(String)
    temperature_control = Column(String)
    target_temperature_spec = Column(String(100), nullable=True)
    hazardous_materials = Column(Boolean, default=False, nullable=False)
    hazchem_classification = Column(String, nullable=True)
    under_bond = Column(Boolean, default=False) ########### Add to DB
    rib_requirements = Column(Boolean, default=False) ####### Add to DB
    packaging_quantity = Column(Integer)
    packaging_type = Column(String)
    distance = Column(Numeric(10, 2), nullable=True)
    estimated_transit_time = Column(String)
    eta_date = Column(Date)
    eta_window = Column(String)
    route_preview_embed = Column(String)
    polyline = Column(String)
    status = Column(String(50), nullable=False, default="Booked")
    trip_status = Column(String(50), nullable=False, default="Schedule")
    pod_document = Column(String, nullable=True)
    vehicle_id = Column(Integer)
    driver_id = Column(Integer)
    # ============================================================
    # RATE INCLUDES
    # ============================================================
    rate_includes_fuel = Column(Boolean, default=False, nullable=False)
    rate_includes_driver = Column(Boolean, default=False, nullable=False)
    rate_includes_maintenance = Column(Boolean, default=False, nullable=False)
    rate_includes_insurance = Column(Boolean, default=False, nullable=False)
    rate_includes_tolls = Column(Boolean, default=False, nullable=False)
    rate_includes_border_charges = Column(Boolean, default=False, nullable=False)
    rate_includes_empty_return = Column(Boolean, default=False, nullable=False)
    rate_includes_waiting_time = Column(Boolean, default=False, nullable=False)
    rate_includes_loading_assistance = Column(Boolean, default=False, nullable=False)
    rate_includes_offloading_assistance = Column(Boolean, default=False, nullable=False)
    # ============================================================
    # OPERATIONAL REQUIREMENTS
    # ============================================================
    minimum_weight_bracket_kg = Column(Integer, nullable=False)
    vehicle_tracking_required = Column(Boolean, default=False, nullable=False)
    all_time_hour_control_room = Column(Boolean, default=False, nullable=False)
    driver_mobile_phone = Column(Boolean, default=False, nullable=False)
    clean_compliant_equipment = Column(Boolean, default=False, nullable=False)
    pallet_management = Column(Boolean, default=False, nullable=False)
    pod_submission_local = Column(String, nullable=False)
    pod_submission_long_haul = Column(String, nullable=False)
    pod_submission_cross_border = Column(String, nullable=False)
    # ============================================================
    # INSURANCE REQUIREMENTS
    # ============================================================
    minimum_git_cover_amount = Column(Integer, default=0, nullable=True)
    minimum_liability_cover_amount = Column(Integer, default=0, nullable=True)
    git_all_risk_required = Column(Boolean, default=False, nullable=False)
    git_first_loss_required = Column(Boolean, default=False, nullable=False)
    git_driver_fidelity_required = Column(Boolean, default=False, nullable=False)
    # ============================================================
    # EQUIPMENT COMPLIANCE
    # ============================================================
    tarpaulin_compliance_required = Column(Boolean, default=False, nullable=False)
    corner_plates_required = Column(Boolean, default=False, nullable=False)
    chock_blocks_required = Column(Boolean, default=False, nullable=False)
    ratchets_belts_required = Column(Boolean, default=False, nullable=False)
    other_equipment_requirements = Column(Text, nullable=True)

    created_at = Column(DateTime(timezone=True), default=get_sast_time)
    updated_at = Column(DateTime(timezone=True), default=get_sast_time, onupdate=get_sast_time)


class Assigned_Spot_Ftl_Shipments(Base):
    __tablename__ = "assigned_ftl_shipments"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    shipment_id = Column(Integer, index=True, nullable=False)
    is_subshipment = Column(Boolean, default=False)
    lane_id = Column(Integer, nullable=True)
    type = Column(String, default="FTL")
    pod_document = Column(String, nullable=True)
    invoice_id = Column(Integer, nullable=True) # Update in database
    invoice_due_date = Column(Date, nullable=True) # Update in database
    invoice_status = Column(String, nullable=True) # Update in database
    trip_type = Column(String)
    load_type = Column(String)
    carrier_id = Column(Integer, nullable=False)
    carrier_name = Column(String, nullable=False)
    vehicle_id = Column(Integer, nullable=True)
    live_location = Column(String)
    driver_id = Column(Integer, nullable=True)
    accepted_for = Column(String)
    accepted_at = Column(String)
    minimum_weight_bracket = Column(Integer, nullable=False)
    minimum_git_cover_amount = Column(Integer, default=0, nullable=True)
    minimum_liability_cover_amount = Column(Integer, default=0, nullable=True)
    shipment_rate = Column(Integer, nullable=False)
    distance = Column(Integer, nullable=False)
    rate_per_km = Column(Integer, nullable=False)
    rate_per_ton = Column(Integer, nullable=False)
    payment_terms = Column(String, nullable=False)
    status = Column(String, default="Assigned")
    trip_status = Column(String, default="Scheduled")
    required_truck_type = Column(String, nullable=True)
    equipment_type = Column(String, nullable=True)
    trailer_type = Column(String, nullable=True)
    trailer_length = Column(String, nullable=True)
    origin_address = Column(String)
    origin_address_completed = Column(String)
    origin_city_province = Column(String)
    origin_country = Column(String)
    origin_region = Column(String)
    stop_1_address = Column(String, nullable=True)
    stop_2_address = Column(String, nullable=True)
    stop_3_address = Column(String, nullable=True)
    stop_4_address = Column(String, nullable=True)
    stop_5_address = Column(String, nullable=True)
    destination_address = Column(String)
    destination_address_completed = Column(String)
    destination_city_province = Column(String)
    destination_country = Column(String)
    destination_region = Column(String)
    route_preview_embed = Column(String, nullable=True)
    pickup_date = Column(Date)
    pickup_start_time = Column(Time)
    pickup_appointment = Column(String)
    priority_level = Column(String, nullable=True)
    customer_reference_number = Column(String)
    shipment_weight = Column(Integer)
    commodity = Column(String)
    temperature_control = Column(String)
    hazardous_materials = Column(Boolean, nullable=False)
    packaging_quantity = Column(String)
    packaging_type = Column(String)
    pickup_number = Column(String)
    pickup_notes = Column(String)
    delivery_number = Column(String)
    delivery_notes = Column(String)
    estimated_transit_time = Column(String)
    pickup_facility_id = Column(Integer)
    pickup_facility_rating = Column(Float, default=0.0, nullable=True)
    stop_1_facility_id = Column(Integer, nullable=True)
    stop_2_facility_id = Column(Integer, nullable=True)
    stop_3_facility_id = Column(Integer, nullable=True)
    stop_4_facility_id = Column(Integer, nullable=True)
    stop_5_facility_id = Column(Integer, nullable=True)
    delivery_facility_id = Column(Integer)
    delivery_facility_rating = Column(Float, default=0.0, nullable=True)
    eta_window = Column(String, nullable=True)
    eta_date = Column(Date, nullable=True)
    created_at = Column(DateTime, nullable=False, server_default=func.now())
    updated_at = Column(DateTime, nullable=True, onupdate=func.now())


class Assigned_Power_Shipments(Base):
    __tablename__ = "assigned_power_shipments"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    shipment_id = Column(Integer, nullable=False)
    is_subshipment = Column(Boolean, default=False)
    lane_id = Column(Integer, nullable=True)
    pod_document = Column(String, nullable=True)
    invoice_id = Column(Integer, nullable=True) # Update in database
    invoice_due_date = Column(Date, nullable=True) # Update in database
    invoice_status = Column(String, nullable=True) # Update in database
    type = Column(String, default="POWER")
    trip_type = Column(String)
    load_type = Column(String)
    carrier_id = Column(Integer, nullable=False)
    carrier_name = Column(String, nullable=False)
    vehicle_id = Column(Integer, nullable=True)
    trailer_id = Column(Integer)
    driver_id = Column(Integer, nullable=True)
    accepted_for = Column(String)
    accepted_at = Column(String)
    minimum_weight_bracket = Column(Integer, nullable=False)
    minimum_git_cover_amount = Column(Integer, default=0, nullable=True)
    minimum_liability_cover_amount = Column(Integer, default=0, nullable=True)
    shipment_rate = Column(Integer, nullable=False)
    distance = Column(Integer, nullable=False)
    rate_per_km = Column(Integer, nullable=False)
    rate_per_ton = Column(Integer, nullable=False)
    payment_terms = Column(Integer, nullable=False)
    status = Column(Enum("Assigned", "In-Progress", "Completed", "Cancelled"), default="Assigned")
    trip_status = Column(Enum("Scheduled", "Carrier En-route to pickup", " Carrier at pickup facility", "Loading",
                              "Carrier in transit", "Carrier at delivery facility", "Off-loading", "Completed", "Cancelled"), default="Scheduled")
    required_truck_type = Column(String, nullable=True)
    axle_configuration = Column(String, nullable=True)
    origin_address = Column(String)
    origin_address_completed = Column(String)
    origin_city_province = Column(String)
    origin_country = Column(String)
    origin_region = Column(String)
    pickup_appointment = Column(String)
    destination_address = Column(String)
    destination_address_completed = Column(String)
    destination_city_province = Column(String)
    destination_country = Column(String)
    destination_region = Column(String)
    delivery_appointment = Column(String)
    route_preview_embed = Column(String, nullable=True)
    pickup_date = Column(Date)
    pickup_start_time = Column(Time)
    priority_level = Column(String, nullable=True)
    customer_reference_number = Column(String)
    shipment_weight = Column(Integer)
    commodity = Column(String)
    temperature_control = Column(String)
    hazardous_materials = Column(String, nullable=False)
    packaging_quantity = Column(String)
    packaging_type = Column(String)
    pickup_number = Column(String)
    pickup_notes = Column(String)
    delivery_number = Column(String)
    delivery_notes = Column(String)
    estimated_transit_time = Column(String)
    is_trailer_loaded = Column(Boolean)
    pickup_facility_id = Column(Integer)
    pickup_facility_rating = Column(Float, default=0.0, nullable=True)
    delivery_facility_id = Column(Integer)
    delivery_facility_rating = Column(Float, default=0.0, nullable=True)
    eta_window = Column(String, nullable=True)
    eta_date = Column(Date, nullable=True)
    created_at = Column(DateTime, nullable=False, server_default=func.now())
    updated_at = Column(DateTime, nullable=True, onupdate=func.now())