from sqlalchemy import Boolean, Integer, String, Column, Float, Date, DateTime, Enum, func
from models.base import Base
from utils.sast_datetime import get_sast_time

class FTL_SHIPMENT(Base):
    __tablename__ = "ftl_shipments"

    id = Column(Integer, index=True, primary_key=True)
    is_subshipment = Column(Boolean, default=False, nullable=False)
    dedicated_lane_id = Column(Integer, nullable=True)
    type = Column(String, default="FTL")
    trip_type = Column(String, nullable=False)
    load_type = Column(String, nullable=False)
    shipper_company_id = Column(Integer)
    shipper_user_id = Column(Integer)
    consignor_id = Column(Integer)
    payment_terms = Column(String, nullable=False)
    invoice_id = Column(Integer, nullable=False)
    invoice_due_date = Column(Date, nullable=True)
    invoice_status = Column(String, nullable=False)
    minimum_git_cover_amount = Column(Integer, default=0, nullable=True)
    minimum_liability_cover_amount = Column(Integer, default=0, nullable=True)
    required_truck_type = Column(String, nullable=False)
    equipment_type = Column(String, nullable=False)
    trailer_type = Column(String, nullable=True)
    trailer_length = Column(String, nullable=True)
    minimum_weight_bracket = Column(Integer, nullable=False)
    origin_address = Column(String)
    complete_origin_address = Column(String)
    origin_city_province = Column(String)
    origin_country = Column(String)
    origin_region = Column(String)
    destination_address = Column(String)
    complete_destination_address = Column(String)
    destination_city_province = Column(String)
    destination_country = Column(String)
    destination_region = Column(String)
    pickup_date = Column(Date)
    pickup_appointment = Column(String)
    priority_level = Column(String, nullable=True)
    pickup_facility_id = Column(Integer)
    delivery_facility_id = Column(Integer)
    customer_reference_number = Column(String)
    shipment_weight = Column(Integer)
    commodity = Column(String)
    temperature_control = Column(String)
    hazardous_materials = Column(String, nullable=False)
    packaging_quantity = Column(String)
    packaging_type = Column(String)
    pickup_number = Column(String)
    pickup_notes = Column(String)
    delivery_number = Column(String)
    delivery_notes = Column(String)
    distance = Column(Integer, nullable=True)
    estimated_transit_time = Column(String)
    eta_date = Column(Date)
    eta_window = Column(String)
    route_preview_embed = Column(String)
    polyline = Column(String)
    quote = Column(Integer)
    shipment_status = Column(String, nullable=True)
    trip_status = Column(String, nullable=True)
    pod_document = Column(String, nullable=True)
    carrier_id = Column(Integer)
    carrier_name = Column(String, default="SADC FREIGHTLINK Sub-contractor")
    carrier_git_cover_amount = Column(Integer, nullable=True)
    carrier_liability_cover_amount = Column(Integer, nullable=True)
    vehicle_id = Column(Integer)
    vehicle_make = Column(String)
    vehicle_model = Column(String)
    vehicle_year = Column(String)
    vehicle_color = Column(String)
    vehicle_license_plate = Column(String)
    vehicle_vin = Column(String, nullable=True)
    vehicle_type = Column(String, nullable=True)
    vehicle_equipment_type = Column(String, nullable=True)
    vehicle_trailer_type = Column(String, nullable=True)
    vehicle_trailer_length = Column(String, nullable=True)
    vehicle_tare_weight = Column(Integer, nullable=True)
    vehicle_gvm_weight = Column(Integer, nullable=True)
    vehicle_payload_capacity = Column(Integer, nullable=True)
    driver_id = Column(Integer)
    driver_first_name = Column(String)
    driver_last_name = Column(String)
    driver_license_number = Column(String)
    driver_email = Column(String)
    driver_phone_number = Column(String)
    created_at = Column(DateTime(timezone=True), default=get_sast_time)
    updated_at = Column(DateTime(timezone=True), default=get_sast_time, onupdate=get_sast_time)


class FTL_Shipment_Docs(Base):
    __tablename__ = "ftl_shipment_docs"

    id = Column(Integer, index=True, primary_key=True)
    shipment_id = Column(Integer)
    commercial_invoice = Column(String, nullable=True)
    packaging_list = Column(String, nullable=True)
    customs_declaration_form = Column(String, nullable=True)
    import_or_export_permits = Column(String, nullable=True)
    certificate_of_origin = Column(String, nullable=True)
    da5501orsad500 = Column(String, nullable=True)
    created_at = Column(DateTime(timezone=True), default=get_sast_time)
    updated_at = Column(DateTime(timezone=True), default=get_sast_time, onupdate=get_sast_time)


class FTL_Shipment_Dispute(Base):
    __tablename__ = "ftl_shipment_disputes"

    id = Column(Integer, index=True, primary_key=True)
    filed_by_shipper = Column(Boolean)
    shipment_id = Column(Integer, nullable=False)
    shipper_company_id = Column(Integer, nullable=False)
    carrier_company_id = Column(Integer, nullable=False)
    dispute_reason = Column(String, nullable=False)
    additional_details = Column(String, nullable=True)
    status = Column(Enum("Open", "Closed"), default="Open")
    created_at = Column(DateTime(timezone=True), default=get_sast_time)
    updated_at = Column(DateTime(timezone=True), default=get_sast_time, onupdate=get_sast_time)