from models.base import Base
from utils.sast_datetime import get_sast_time

class Platform_Super_Admins(Base):
    __tablename__ = "platform_super_admins"

    id = Column(Integer, primary_key=True, autoincrement=True)
    first_name = Column(String, nullable=False)
    last_name = Column(String, nullable=False)
    id_number = Column(String, nullable=False)
    nationality = Column(String, nullable=False)
    home_address = Column(String, nullable=False)
    email = Column(String, nullable=False)
    phone_number = Column(String, nullable=False)
    password = Column(String, nullable=False)
    status = Column(String, nullable=False)
    created_at = Column(DateTime(timezone=True), default=get_sast_time)
    updated_at = Column(DateTime(timezone=True), default=get_sast_time, onupdate=get_sast_time)

class Platform_Support_Admins(Base):
    __tablename__ = "platform_support_admins"

    id = Column(Integer, primary_key=True, autoincrement=True)
    first_name = Column(String, nullable=False)
    last_name = Column(String, nullable=False)
    id_number = Column(String, nullable=False)
    nationality = Column(String, nullable=False)
    home_address = Column(String, nullable=False)
    email = Column(String, nullable=False)
    phone_number = Column(String, nullable=False)
    password = Column(String, nullable=False)
    status = Column(String, nullable=False)
    created_at = Column(DateTime(timezone=True), default=get_sast_time)
    updated_at = Column(DateTime(timezone=True), default=get_sast_time, onupdate=get_sast_time)

class Platform_Super_and_Support_Admins_Permissions(Base):
    __tablename__ = "platform_super_and_support_admins_permissions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    platform_support_admin_id = Column(Integer, ForeignKey("platform_support_admins.id"))
    platform_super_admin_id = Column(Integer, ForeignKey("platform_super_admins.id"))
    cancel_shipments = Column(Boolean, default=False)
    create_shipments = Column(Boolean, default=False)
    update_shipments = Column(Boolean, default=False)
    delete_shipments = Column(Boolean, default=False)
    cancel_lanes = Column(Boolean, default=False)
    create_lanes = Column(Boolean, default=False)
    update_lanes = Column(Boolean, default=False)
    delete_lanes = Column(Boolean, default=False)
    cancel_shipment_exchanges = Column(Boolean, default=False)
    create_shipment_exchanges = Column(Boolean, default=False)
    update_shipment_exchanges = Column(Boolean, default=False)
    delete_shipment_exchanges = Column(Boolean, default=False)
    cancel_lane_exchanges = Column(Boolean, default=False)
    create_lane_exchanges = Column(Boolean, default=False)
    update_lane_exchanges = Column(Boolean, default=False)
    delete_lane_exchanges = Column(Boolean, default=False)
    verify_shipper_companies = Column(Boolean, default=False)
    verify_shipper_financial_accounts = Column(Boolean, default=False)
    verify_shipper_users = Column(Boolean, default=False)
    activate_shipper_companies = Column(Boolean, default=False)
    activate_shipper_financial_accounts = Column(Boolean, default=False)
    activate_shipper_users = Column(Boolean, default=False)
    suspend_shipper_companies = Column(Boolean, default=False)
    suspend_shipper_financial_accounts = Column(Boolean, default=False)
    suspend_shipper_users = Column(Boolean, default=False)
    verify_carrier_companies = Column(Boolean, default=False)
    verify_carrier_financial_accounts = Column(Boolean, default=False)
    verify_carrier_users = Column(Boolean, default=False)
    activate_carrier_companies = Column(Boolean, default=False)
    activate_carrier_financial_accounts = Column(Boolean, default=False)
    activate_carrier_users = Column(Boolean, default=False)
    suspend_carrier_companies = Column(Boolean, default=False)
    suspend_carrier_financial_accounts = Column(Boolean, default=False)
    suspend_carrier_users = Column(Boolean, default=False)
    process_carrier_withdrawal_requests = Column(Boolean, default=False)
    process_shipper_withdrawal_requests = Column(Boolean, default=False)
    close_shipment_disputes = Column(Boolean, default=False)
    close_lane_disputes = Column(Boolean, default=False)
    close_invoice_disputes = Column(Boolean, default=False)
    credit_shipper_financial_accounts = Column(Boolean, default=False)
    debit_shipper_financial_accounts = Column(Boolean, default=False)
    manage_shipper_spending_credit_limit = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), default=get_sast_time)
    updated_at = Column(DateTime(timezone=True), default=get_sast_time, onupdate=get_sast_time)