from enum import StrEnum
from sqlalchemy import event
from sqlalchemy.orm import relationship, remote
from sqlalchemy import Column, String, Integer, DateTime, Date, ForeignKey, Enum, Float, Boolean, func
from enums import Axle_Configuration, CarrierType, TrailerType, TruckType
from models.base import Base
from sqlalchemy import Enum as SqlEnum

class Vehicle(Base):
    __tablename__ = "vehicles"

    id = Column(Integer, primary_key=True, index=True)
    type = Column(String, nullable=True)
    make = Column(String, nullable=False)
    model = Column(String, nullable=False)
    year = Column(Integer, nullable=False)
    color = Column(String, nullable=False)
    axle_configuration = Column(String, nullable=False)
    vin = Column(String, unique=True, nullable=False)
    license_plate = Column(String, unique=True, nullable=False)
    license_expiry_date = Column(Date, nullable=False)
    tare_weight = Column(Integer, nullable=False)
    gvm_weight = Column(Integer, nullable=False)
    tracker_providers_name = Column(String, nullable=False)
    tracker_providers_country = Column(String, nullable=False)
    tracker_id = Column(String, nullable=False)
    tracker_login_username = Column(String, nullable=False)
    tracker_login_password = Column(String, nullable=False)
    tracker_api_username = Column(String, nullable=False)
    tracker_api_token = Column(String, nullable=False)
    payload_capacity = Column(Integer, nullable=False)
    trailer_id = Column(Integer, nullable=True)
    equipment_type = Column(String, nullable=True)
    trailer_type = Column(String, nullable=True)
    trailer_length = Column(String, nullable=True)
    primary_driver_id = Column(Integer, nullable=True)
    secondary_driver_id = Column(Integer, nullable=True)
    owner_id = Column(Integer, nullable=True)
    company_name = Column(String, nullable=True)
    company_type = Column(String, nullable=True)
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)
    speed = Column(Integer, default=0, nullable=True)
    heading = Column(Integer, default=0, nullable=True)
    location_description = Column(String, nullable=True)
    time_stamp = Column(DateTime)  # When this data was fetched
    current_shipment_id = Column(Integer, nullable=True)
    current_shipment_type = Column(String, nullable=True)
    total_shipments_completed = Column(Integer, default=0, nullable=False)
    vrc_or_leasing = Column(String, nullable=False)
    vehicle_license_disk = Column(String, nullable=False)
    vehicle_road_worthy_certificate = Column(String, nullable=True)
    vehicle_tracking_certificate = Column(String, nullable=False)
    front_angle_image = Column(String, nullable=False)
    rear_angle_image = Column(String, nullable=False)
    left_angle_image = Column(String, nullable=False)
    right_angle_image = Column(String, nullable=False)
    is_verified = Column(Boolean, default=False)
    status = Column(Enum("Un-verified", "Active", "Under Investigation", "Suspended"), default="Un-verified") #Update in Database
    service_status = Column(String) #################Update in database
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

class Vehicle_Schedule(Base):
    __tablename__ = "vehicle_schedules"

    id = Column(Integer, primary_key=True, index=True)
    vehicle_id = Column(Integer)
    status = Column(String)
    shipment_id = Column(Integer)
    shipment_type = Column(String)
    origin = Column(String)
    destination = Column(String)
    pickup_appointment = Column(String)
    eta = Column(String)
    distance = Column(Integer)
    rate = Column(Integer)
    commodity = Column(String)
    weight = Column(Integer)
    past = Column(Boolean, default=False)

class Trailer(Base):
    __tablename__ = "trailers"

    id = Column(Integer, primary_key=True, index=True)
    make = Column(String, nullable=False)
    model = Column(String, nullable=False)
    year = Column(Integer, nullable=False)
    color = Column(String, nullable=False)
    equipment_type = Column(String, nullable=False)
    trailer_type = Column(String, nullable=False)
    trailer_length = Column(String, nullable=False)
    vin = Column(String, unique=True, nullable=False)
    license_plate = Column(String, unique=True, nullable=False)
    license_expiry_date = Column(Date, nullable=False)
    tare_weight = Column(Integer, nullable=False)
    gvm_weight = Column(Integer, nullable=False)
    payload_capacity = Column(Integer, nullable=False)
    owner_id = Column(Integer, nullable=False)
    company_name = Column(String, nullable=True)
    company_type = Column(String, nullable=True)
    truck_id = Column(Integer, nullable=True)
    vrc_leasing = Column(String, nullable=False)
    license_disk = Column(String, nullable=False)
    road_worthy_certificate = Column(String, nullable=True)
    front_angle_image = Column(String, nullable=False)
    rear_angle_image = Column(String, nullable=False)
    left_angle_image = Column(String, nullable=False)
    right_angle_image = Column(String, nullable=False)
    is_verified = Column(Boolean, default=False)
    is_vehicle = Column(Boolean, default=True)
    status = Column(Enum("Un-verified", "Active", "Under Investigation", "Suspended"), default="Un-verified") #Update in Database
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

class ShipperTrailer(Base):
    __tablename__ = "shipper_trailers"

    id = Column(Integer, primary_key=True, index=True)
    make = Column(String, nullable=False)
    model = Column(String, nullable=False)
    year = Column(Integer, nullable=False)
    color = Column(String, nullable=False)
    equipment_type = Column(String, nullable=False)
    trailer_type = Column(String, nullable=False)
    trailer_length = Column(String, nullable=False)
    vin = Column(String, unique=True, nullable=False)
    license_plate = Column(String, unique=True, nullable=False)
    license_expiry_date = Column(Date, nullable=False)
    tare_weight = Column(Integer, nullable=False)
    gvm_weight = Column(Integer, nullable=False)
    payload_capacity = Column(Integer, nullable=False)
    owner_id = Column(Integer, nullable=False)
    company_name = Column(String, nullable=True)
    company_type = Column(String, nullable=True)
    truck_id = Column(Integer, nullable=True)
    current_shipment_id = Column(Integer, nullable=True)
    current_shipment_status = Column(String, nullable=True)
    vrc_leasing = Column(String, nullable=False)
    license_disk = Column(String, nullable=False)
    road_worthy_certificate = Column(String, nullable=True)
    front_angle_image = Column(String, nullable=False)
    rear_angle_image = Column(String, nullable=False)
    left_angle_image = Column(String, nullable=False)
    right_angle_image = Column(String, nullable=False)
    is_verified = Column(Boolean, default=False)
    is_vehicle = Column(Boolean, default=True)
    status = Column(Enum("Un-verified", "Active", "Under Investigation", "Suspended"), default="Un-verified") #Update in Database
    availability_status = Column(Enum("Available", "In Use", "Maintenance"), default="Available", nullable=False)
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())